version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: app
    restart: always
    entrypoint: ./.docker/entrypoint.sh
    environment:
      APP_NAME: 'my-app'
    networks:
      - myapp-network
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: mysql
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /home/db
      - ./.docker/database.sql:/docker-entrypoint-initdb.d/database.sql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - myapp-network

networks:
  myapp-network:      